-- Supabase Schema Initialization for KWE POS System

-- Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Suppliers Table
CREATE TABLE IF NOT EXISTS public.suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact TEXT,
  phone TEXT,
  balance NUMERIC DEFAULT 0,
  bank_name TEXT,
  bank_account_name TEXT,
  bank_account_no TEXT,
  bank_routing_no TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Units Table
CREATE TABLE IF NOT EXISTS public.units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  short_name TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Brands Table
CREATE TABLE IF NOT EXISTS public.brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES public.categories(id),
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Currencies Table
CREATE TABLE IF NOT EXISTS public.currencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  rate NUMERIC DEFAULT 1.0,
  symbol TEXT,
  is_base BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'active'
);

-- Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  barcode TEXT UNIQUE,
  category_id BIGINT REFERENCES public.categories(id),
  brand_id BIGINT REFERENCES public.brands(id),
  unit_id BIGINT REFERENCES public.units(id),
  purchase_price NUMERIC NOT NULL,
  selling_price NUMERIC NOT NULL,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  supplier_id BIGINT REFERENCES public.suppliers(id),
  is_credit_allowed BOOLEAN DEFAULT TRUE,
  expiry_enabled BOOLEAN DEFAULT FALSE,
  is_favorite BOOLEAN DEFAULT FALSE,
  expiry_date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rfid_card TEXT UNIQUE,
  name TEXT NOT NULL,
  phone TEXT,
  credit_limit NUMERIC DEFAULT 0,
  daily_limit NUMERIC DEFAULT 0,
  daily_used NUMERIC DEFAULT 0,
  monthly_limit NUMERIC DEFAULT 0,
  monthly_used NUMERIC DEFAULT 0,
  current_balance NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'active',
  credit_status TEXT DEFAULT 'ACTIVE',
  last_scan_at TIMESTAMPTZ,
  auto_sale_cfg INTEGER DEFAULT 0,
  working_place TEXT,
  emp_id TEXT,
  passport_no TEXT,
  auto_burn_start_date TIMESTAMPTZ,
  auto_burn_stop_date TIMESTAMPTZ,
  auto_burn BOOLEAN DEFAULT FALSE,
  member_type TEXT DEFAULT 'DELIVERY', -- 'DELIVERY' or 'WALKIN'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Purchase Invoices Table
CREATE TABLE IF NOT EXISTS public.purchase_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT UNIQUE NOT NULL,
  supplier_id BIGINT REFERENCES public.suppliers(id),
  total_amount NUMERIC NOT NULL,
  paid_amount NUMERIC DEFAULT 0,
  due_amount NUMERIC NOT NULL,
  payment_status TEXT DEFAULT 'CREDIT',
  status TEXT DEFAULT 'ACTIVE',
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stock Batches Table
CREATE TABLE IF NOT EXISTS public.stock_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id),
  batch_number TEXT,
  expiry_date TEXT,
  quantity INTEGER NOT NULL,
  received_date TEXT,
  purchase_invoice_id BIGINT REFERENCES public.purchase_invoices(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sales Table
CREATE TABLE IF NOT EXISTS public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_amount NUMERIC NOT NULL,
  discount_amount NUMERIC DEFAULT 0,
  payment_method TEXT NOT NULL,
  customer_id BIGINT REFERENCES public.customers(id),
  status TEXT DEFAULT 'completed',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto Burn Sales Table
CREATE TABLE IF NOT EXISTS public.auto_burn_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.customers(id),
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'SYSTEM_GENERATED',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sales Summary Logs Table
CREATE TABLE IF NOT EXISTS public.sales_summary_logs (
  date TEXT PRIMARY KEY,
  total_real_sales NUMERIC DEFAULT 0,
  total_credit_sales NUMERIC DEFAULT 0,
  total_auto_burn_sales NUMERIC DEFAULT 0,
  total_online_sales NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sale Items Table
CREATE TABLE IF NOT EXISTS public.sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.sales(id),
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER NOT NULL,
  unit_price NUMERIC NOT NULL,
  subtotal NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Supplier Returns Table
CREATE TABLE IF NOT EXISTS public.supplier_returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id BIGINT REFERENCES public.suppliers(id),
  total_amount NUMERIC NOT NULL,
  return_type TEXT NOT NULL,
  notes TEXT,
  document_reference TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Supplier Return Items Table
CREATE TABLE IF NOT EXISTS public.supplier_return_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id BIGINT REFERENCES public.supplier_returns(id),
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER NOT NULL,
  unit_cost NUMERIC NOT NULL,
  total_cost NUMERIC NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sales Returns Table
CREATE TABLE IF NOT EXISTS public.sales_returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.sales(id),
  total_refund NUMERIC NOT NULL,
  refund_type TEXT NOT NULL,
  payment_status TEXT DEFAULT 'UNPAID',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sales Return Items Table
CREATE TABLE IF NOT EXISTS public.sales_return_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id BIGINT REFERENCES public.sales_returns(id),
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER NOT NULL,
  refund_amount NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stock Movements Table
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER NOT NULL,
  type TEXT NOT NULL,
  reference_type TEXT NOT NULL,
  reference_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Credit Limit History Table
CREATE TABLE IF NOT EXISTS public.credit_limit_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.customers(id),
  old_limit NUMERIC,
  new_limit NUMERIC,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Credit Status Logs Table
CREATE TABLE IF NOT EXISTS public.credit_status_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.customers(id),
  previous_status TEXT,
  new_status TEXT,
  changed_by BIGINT REFERENCES public.users(id),
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Credit Logs Table
CREATE TABLE IF NOT EXISTS public.credit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.customers(id),
  amount NUMERIC NOT NULL,
  type TEXT NOT NULL,
  reference_id TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Activity Logs Table
CREATE TABLE IF NOT EXISTS public.user_activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id),
  action TEXT NOT NULL,
  target_id BIGINT,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Void Logs Table
CREATE TABLE IF NOT EXISTS public.void_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.sales(id),
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER,
  reason TEXT,
  void_by BIGINT REFERENCES public.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily Credit Logs Table
CREATE TABLE IF NOT EXISTS public.daily_credit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.customers(id),
  burned_amount NUMERIC NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Monthly Credit Logs Table
CREATE TABLE IF NOT EXISTS public.monthly_credit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES public.customers(id),
  usage_amount NUMERIC NOT NULL,
  month TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto Sales Config Table
CREATE TABLE IF NOT EXISTS public.auto_sales_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  product_id BIGINT REFERENCES public.products(id),
  is_active BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RFID Scans Table
CREATE TABLE IF NOT EXISTS public.rfid_scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rfid_card TEXT NOT NULL,
  customer_name TEXT,
  status TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inventory Sessions Table
CREATE TABLE IF NOT EXISTS public.inventory_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  created_by BIGINT REFERENCES public.users(id),
  total_system_value NUMERIC DEFAULT 0,
  total_physical_value NUMERIC DEFAULT 0,
  total_difference NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'DRAFT',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inventory Items Table
CREATE TABLE IF NOT EXISTS public.inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id BIGINT REFERENCES public.inventory_sessions(id),
  product_id BIGINT REFERENCES public.products(id),
  system_stock INTEGER NOT NULL,
  physical_stock INTEGER NOT NULL,
  difference INTEGER NOT NULL,
  buying_price NUMERIC NOT NULL,
  selling_price NUMERIC NOT NULL,
  value_difference NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inventory Audit Logs Table
CREATE TABLE IF NOT EXISTS public.inventory_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id BIGINT REFERENCES public.inventory_sessions(id),
  user_id BIGINT REFERENCES public.users(id),
  action TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Purchase Invoice Items Table
CREATE TABLE IF NOT EXISTS public.purchase_invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES public.purchase_invoices(id),
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER NOT NULL,
  bonus_qty INTEGER DEFAULT 0,
  unit_price NUMERIC NOT NULL,
  total_price NUMERIC NOT NULL,
  batch_number TEXT,
  expiry_date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Purchase Invoice Payments Table
CREATE TABLE IF NOT EXISTS public.purchase_invoice_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES public.purchase_invoices(id),
  amount NUMERIC NOT NULL,
  payment_method TEXT DEFAULT 'CASH',
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  description TEXT,
  amount NUMERIC NOT NULL,
  date TEXT NOT NULL,
  payment_method TEXT DEFAULT 'CASH',
  created_by BIGINT REFERENCES public.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Purchase Invoice Audit Logs Table
CREATE TABLE IF NOT EXISTS public.purchase_invoice_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES public.purchase_invoices(id),
  user_id BIGINT REFERENCES public.users(id),
  old_data TEXT,
  new_data TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Financial Audit Logs Table
CREATE TABLE IF NOT EXISTS public.financial_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  reference_id TEXT,
  user_id BIGINT REFERENCES public.users(id),
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Deleted Returns Logs Table
CREATE TABLE IF NOT EXISTS public.deleted_returns_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id BIGINT REFERENCES public.supplier_returns(id),
  deleted_by BIGINT REFERENCES public.users(id),
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stock Adjustments Table
CREATE TABLE IF NOT EXISTS public.stock_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id),
  adjustment_type TEXT NOT NULL, -- IN / OUT
  quantity NUMERIC NOT NULL,
  reason TEXT NOT NULL,
  note TEXT,
  previous_stock NUMERIC,
  new_stock NUMERIC,
  buying_price NUMERIC,
  created_by BIGINT REFERENCES public.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  inventory_item_id BIGINT REFERENCES public.inventory_items(id) UNIQUE -- Link to audit item
);

-- Migrations to add banking details to existing suppliers table
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS bank_account_name TEXT;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS bank_account_no TEXT;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS bank_routing_no TEXT;

-- Migration to add created_at to existing tables missing it
ALTER TABLE public.units ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.brands ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.supplier_return_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.sales_return_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.purchase_invoice_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

